# Site settings
title: Your awesome title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

# Directory settings
source: ./source
destination: ./build
plugins: ./plugins

# Asset Pipeline settings
assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - ../components

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "projects"
    values:
      featured: false
      weight: 100
